### ISSUE TITLE
dmarcts-report-viewer.php Blank web page

### ISSUE THREAD

**Issue by SamosHaven** [techsneeze/dmarcts-report-viewer#12]
I'm trying to run dmarcts-report-viewer on my local host set up using apache2. I have moved the dmarcts report-parser folder along with all the other files into the /var/www/html directory. My issue is that when I direct the browser to 127.0.0.1/dmarcts-report-parser/dmarcts-report-viewer/dmarcts-report-viewer.php, it shows a blank white web page.

I'm running this on a Linux Ubuntu VM.

Using php7.1 as I encountered a few errors with php5 and ubuntu. 

I know the directory is correctly linked to the php file as I removed the <?php tag and the same web page displayed all the code in the file, but it wont display the SQL database.

I have also checked my SQL database on my localhost and it is populated using dmarcts-report-parser.

Error Log from apache:

 **[Fri Sep 22 15:55:50.307842 2017] [php7:error] [pid 12389] [client 127.0.0.1:54908] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/dmarcts-report-parser/dmarcts-report-viewer/dmarcts-report-viewer.php:216\nStack trace:\n#0 {main}\n  thrown in /var/www/html/dmarcts-report-parser/dmarcts-report-viewer/dmarcts-report-viewer.php on line 216, referer: http://127.0.0.1/dmarcts-report-parser/dmarcts-report-viewer/**

Cheers

**Comment by lwt-pressy** [comment]
The Problem is "Uncaught Error: Class 'mysqli' not found. You are missing the mysql perl package. Under Debian it would be  the package **_libdbd-mysql-perl_**. Under Ubuntu it should be the same.

**Comment by SamosHaven** [comment]
@lwt-pressy I have installed the libdbd-mysql-perl package and still getting the same error. I have restarted apache2 and still nothing is being displayed on the web server.

**Comment by SamosHaven** [comment]
Fixed it by using apt-get install php7.2-mysqli. Not sure why but the package you used looked like it wasn't installing anything as nothing was showing after i used the 'php -m | grep -i mysql' command. Cheers

**Comment by lwt-pressy** [comment]
thx for the feedback. I had a twist in my brain, the viewer ist php and not perl, that why you need php-mysql (meta package without version number). Youre package (php7.2-mysql)  is also fine.
