### ISSUE TITLE
Query failed: GROUP BY

### ISSUE THREAD

**Issue by blizzard4591** [techsneeze/dmarcts-report-viewer#29]
I am having a problem with running the viewer. I get the following error message:

> Query failed: 'dmarc.report.mindate' isn't in GROUP BY (Error #1055)

This is a system running Debian 9, MariaDB 10.1, PHP Version 7.0.30-0+deb9u1.
Do you have an idea of what I am doing wrong? I think one issue could be that my MariaDB server has strict mode enabled, which entails ONLY_FULL_GROUP_BY (https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by).

**Comment by techsneeze** [comment]
My guess is that you aren't doing anything wrong.  If you disable the strict mode on MariaDB, does it seem to work?  
I don't have experience with this specific error, and I think it is the first time it is reported.  I suspect that you would need to add "mindate" to line 475, as part of the GROUP BY statement.  Is that something you'd be able to try as well?
