### ISSUE TITLE
Nothing is showed by the app

### ISSUE THREAD

**Issue by somepad** [techsneeze/dmarcts-report-viewer#31]
$ mysql -V
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
$ php-fpm -v
PHP 5.3.3 (fpm-fcgi) (built: Mar 22 2017 12:28:05)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies

Nothing is showed by the app except default html.
Tried to run from cli, got this error:

php dmarcts-report-viewer.php > /dev/null
PHP Notice:  Undefined offset: 1 in /usr/share/nginx/html/dmarcts-report-viewer/dmarcts-report-viewer.php on line 76
PHP Warning:  Invalid argument supplied for foreach() in /usr/share/nginx/html/dmarcts-report-viewer/dmarcts-report-viewer.php on line 76

Am I missing something?

**Comment by techsneeze** [comment]
It appears as if you may have missed the directions in the README file: 
https://github.com/techsneeze/dmarcts-report-viewer/blob/master/README.md

You should navigate to the path of dmarcts-report-viewer.php via a web browser, and the file needs to be served by a web server (example Apache).  It won't work to just open directly in a browser, and not on the command-line.

It also expects that you have already populated the database with info from https://github.com/techsneeze/dmarcts-report-parser

Did you copy/edit the config file?  Are you serving it via a web server?  Have you already populated the database with the parser?

**Comment by somepad** [comment]
@techsneeze I've done everything you mentioned.
Took a closer look to what parser does and see this for all messages:
Use of uninitialized value $message in substitution (s///) at dmarcts-report-parser.pl line 441.
Could not find an embedded ZIP! The IMAP message with UID #1306 does not seem to contain a valid DMARC report. Skipped.

Could it be because almost all messages contain attachments as gzips? (xml.gz)

**Comment by somepad** [comment]
$imapignoreerror fixed everything.
