### ISSUE TITLE
Make this project ready for inclusion into Debian

### ISSUE THREAD

**Issue by sunweaver** [techsneeze/dmarcts-report-viewer#35]
Hi,

while setting up Rspamd with SPD/DKIM/DMARC on my own mail server recently, I today stumbled over this project. I have deployed it right a away and its awesome as it is simple to setup. Nice work!

Would you mind me to upload this package to Debian? If not, then I'd like to ask you for a release of the current code base (if it is releasable).

Thanks+Greets
Mike (aka sunweaver at debian.org)

**Comment by techsneeze** [comment]
Sorry for the extremely long delay!  I've been focused on other projects, but recent events have allowed me to circle back here!  I'm great with you uploading to Debian if you find it useful.
