### ISSUE TITLE
[Request] Default sort order

### ISSUE THREAD

**Issue by Taomyn** [techsneeze/dmarcts-report-viewer#36]
I would like to recommend option to set the following:

- Sort order by "end date" - reason, when a report from 24th Oct to 27th Nov comes in on 28th Nov, you don't see it because the list is sorted by start date, and so only appears if you view data for October or change the display period to all

I achieved this myself by swapping the "order by" mindate/maxdate of the SQL

**Comment by techsneeze** [comment]
I'm interested in seeing more.  Can you submit a Pull request with the changes you've done and have in mind?
