### ISSUE TITLE
ajax version isn't displaying anything

### ISSUE THREAD

**Issue by Nothing4You** [techsneeze/dmarcts-report-viewer#42]
opening the page as of b5b805531b997924409e737dbccb8caf8767bf32 shows the following errors in console:

```
Uncaught TypeError: document.getElementById(...) is null
    showReportlist https://myhost/dmarcts-report-viewer/dmarcts-report-viewer.js:95
    onload https://myhost/dmarcts-report-viewer/dmarcts-report-viewer.php:1
```

I can also not see `selDomain` in the page source in the browser, which causes the exception.

disclaimer: this is a fresh install, i don't know if it's actually related to the recent changes

**Comment by Nothing4You** [comment]
seems like it's caused by https://github.com/techsneeze/dmarcts-report-viewer/blob/master/dmarcts-report-viewer.php#L100 as i only have a single domain in this setup

**Comment by techsneeze** [comment]
I made a minor change that should account for a single domain.  Can you see if that resolves your issue?

**Comment by Nothing4You** [comment]
That resolves my issue, although if you're reducing check to already match a single domain you could probably drop it entirely.
I believe the logic was intended to hide the domain selection when there's just a single domain, which however isn't working, as the clientside js code does not account for that, as it doesn't handle the `<select>` not being there.

**Comment by techsneeze** [comment]
We've changed things quite a bit, which should be more in line with your expectations!  I'll go ahead and close this for now.
