### ISSUE TITLE
Options Screen

### ISSUE THREAD

**Issue by jnew-gh** [techsneeze/dmarcts-report-viewer#63]
I am creating an options screen for dmarcts to replace the option values in dmarcts-report-viewer-config.php and dmarcts-report-viewer.js. The options would be stored in the database along with the DMARC reports, in a separate table. So far, I have the following options:

- General Settings
  - Host lookup: On/Off
  - Default sort column: dropdown list
  - Default sorting order: Asc/Desc
  - Unknown SPF/DKIM Alignments (treat unknown results as alignment failures or keep as "unknown"): On/Off
- Filters
  - Default DMARC Result: dropdown list
  - Show Only Report Data records that match DMARC Result: On/Off
  - Default Report Data Status: dropdown list
  - Default period: Current Month/All
  - Default domain: dropdown list
  - Default reporter: dropdown list
- Appearance
  - Default css file: dropdown list
  - Report List - Initial Height: number
- Developer
  - Debug messages: On/Off
  - Debug Window - Initial Height: number
  - Debug Window - Maximum Height: number

Some of the above options reference features not yet implemented but planned.

Any suggestions for more options?

**Comment by trogper** [comment]
I think it would be better to store the settings in a cookie or local database (in browser), since there may be more users using the same instance of the viewer

**Comment by jnew-gh** [comment]
Good point.

I had thought about cookie-based option storage. I may look into that as well. Thanks.

**Comment by jnew-gh** [comment]
Closing this issue. Cookie-based options page implemented with PR #65.
