### ISSUE TITLE
Fatal error: Uncaught Error: Class "DOMDocument" not found

### ISSUE THREAD

**Issue by muety** [techsneeze/dmarcts-report-viewer#71]
When clicking on one of the report entries, the following 500 error occurs.

```

Fatal error: Uncaught Error: Class "DOMDocument" not found in /var/www/storage/dmarc/dmarcts-report-viewer-report-data.php:184 Stack trace: #0 /var/www/storage/dmarc/dmarcts-report-viewer-report-data.php(58): formatXML() #1 /var/www/storage/dmarc/dmarcts-report-viewer-report-data.php(321): tmpl_reportData() #2 {main} thrown in /var/www/storage/dmarc/dmarcts-report-viewer-report-data.php on line 184
```

**Comment by jnew-gh** [comment]
You need to have the php DOM extension installed, which is mentioned in the dmarcts-reports-viewer Requirements section in the README.md file.

Depending on your OS and PHP version, the package file name will be some combination of php-, the PHP version number, and  -xml or -dom. See [this topic on stackoverflow](https://stackoverflow.com/questions/14395239/class-domdocument-not-found) for a discussion of the error and some file name examples.

**Comment by muety** [comment]
Sorry, my bad. Should have read the instructions.
