### ISSUE TITLE
Raw Report XML broken

### ISSUE THREAD

**Issue by dave-slaughter** [techsneeze/dmarcts-report-viewer#89]
[commit a5ead0b](https://github.com/techsneeze/dmarcts-report-viewer/commit/a5ead0b9c9e8dff8a66b3aed61145bd454d13e2b) breaks the Raw Report XML.

Rather than showing the actual XML it shows it HTML escaped, so `<pre><code class='xml'>&lt;?xml version=&quot;1.0&quot;` and not `<?xml version="1.0"...`

The problem is in `dmarcts-report-viewer-report-data.php`

```php
$row['raw_xml'] = formatXML($row['raw_xml'], $reportnumber);
$row = array_map('html_escape', $row);
```

which should probably be

```php
$row['raw_xml'] = formatXML($row['raw_xml'], $reportnumber);
foreach ($row as $k => $v) {
	if ($k !== 'raw_xml') {
		$row[$k] = html_escape($v);
	}
}
```

**Comment by techsneeze** [comment]
Thanks for the suggestion, appears to work much better now!
